### ISSUE TITLE
生成后的弹框里面有分页数据，然后执行保存按钮，再打开仅有当前页的数据，其他的数据都丢失了

### ISSUE THREAD

**Issue by dingzaixing** [cq-panda/Vue.NetCore#184]
![1628849224(1)](https://user-images.githubusercontent.com/71482022/129341686-213bfd4f-60e4-4e91-90cc-483c6f0e52be.png)

**Comment by cq-panda** [comment]
每次打开都会刷新明细表数据，不知道你说的其他数据丢失了是什么意思,共176条，变成共100条了吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cq-panda/Vue.NetCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月13日(星期五) 晚上6:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cq-panda/Vue.NetCore] 生成后的弹框里面有分页数据，然后执行保存按钮，再打开仅有当前页的数据，其他的数据都丢失了 (#184)





 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dingzaixing** [comment]
嗯，是的，176条会变成100条数据。所有生成的页面都试了一下，都有同样问题，求大佬指教

**Comment by cq-panda** [comment]
> 嗯，是的，176条会变成100条数据。所有生成的页面都试了一下，都有同样问题，求大佬指教

等这周未更新

**Comment by dingzaixing** [comment]
下面的代码去除掉，应该就可以了
            if (saveModel.DelKeys == null || saveModel.DelKeys.Count == 0)
            {
                saveModel.DelKeys = detailKeys.Cast<object>()
                    .Where(o => !detailList.Any(n => detailKeyInfo.GetValue(n).ToString() == o.ToString()))
                    .Select(t => t).ToList();
            }

**Comment by cq-panda** [comment]
框架不是这样写的，可以检查下你们自己是什么时候修改过的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cq-panda/Vue.NetCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 下午5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cq-panda/Vue.NetCore] 生成后的弹框里面有分页数据，然后执行保存按钮，再打开仅有当前页的数据，其他的数据都丢失了 (#184)





 
下面的代码去除掉，应该就可以了
 if (saveModel.DelKeys == null || saveModel.DelKeys.Count == 0)
 {
 saveModel.DelKeys = detailKeys.Cast()
 .Where(o =&gt; !detailList.Any(n =&gt; detailKeyInfo.GetValue(n).ToString() == o.ToString()))
 .Select(t =&gt; t).ToList();
 }




 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dingzaixing** [comment]
谢谢！
