### ISSUE TITLE
高级查询过滤失效

### ISSUE THREAD

**Issue by shjjwjy** [cq-panda/Vue.NetCore#194]
你好，如下图，我在service重写GetPageData后，页面提交过来的过滤条件，没有生效，能帮看下为啥嘛？
![image](https://user-images.githubusercontent.com/12255214/133537762-1f681aad-396b-4606-bb69-b3f221353db8.png)

**Comment by cq-panda** [comment]
参照后台开发文档上的查询前方法，给QuerySql设置查询语句，下面QueryRelativeExpression不要。如果还不生效，更新下ServiceBase.cs




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cq-panda/Vue.NetCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 上午10:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cq-panda/Vue.NetCore] 高级查询过滤失效 (#194)





 
你好，如下图，我在service重写GetPageData后，页面提交过来的过滤条件，没有生效，能帮看下为啥嘛？
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
