### ISSUE TITLE
富文本编辑器换行问题

### ISSUE THREAD

**Issue by shjjwjy** [cq-panda/Vue.NetCore#195]
我看了下你的例子是写在页面上的，编辑器正常，如果把富文本放到编辑弹出框中，我试了下无法换行， 会有闪跳的现象。

**Comment by cq-panda** [comment]
把编辑器组件更新下，昨天晚上提交了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cq-panda/Vue.NetCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月17日(星期五) 下午3:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cq-panda/Vue.NetCore] 富文本编辑器换行问题 (#195)





 
我看了下你的例子是写在页面上的，编辑器正常，如果把富文本放到编辑弹出框中，我试了下无法换行， 会有闪跳的现象。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shjjwjy** [comment]
好的谢谢
