### ISSUE TITLE
低代码设计器现在可以使用吗？

### ISSUE THREAD

**Issue by LadyKiller1025** [cq-panda/Vue.NetCore#207]
我看了下示例程序，拖拽完了没有地方复制生产的代码

**Comment by cq-panda** [comment]
最近会更新这个功能




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cq-panda/Vue.NetCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 上午8:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cq-panda/Vue.NetCore] 低代码设计器现在可以使用吗？ (Issue #207)





 
我看了下示例程序，拖拽完了没有地方复制生产的代码
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LadyKiller1025** [comment]
> 最近会更新这个功能
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cq-panda/Vue.NetCore" ***@***.***&gt;; 发送时间:&nbsp;2021年12月6日(星期一) 上午8:59 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[cq-panda/Vue.NetCore] 低代码设计器现在可以使用吗？ (Issue #207) 我看了下示例程序，拖拽完了没有地方复制生产的代码 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LadyKiller1025** [comment]
呃呃
